# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: CU Hacky Hour
email: rob.syme@gmail.com
description: A regular meeting for people working with data at Curtin.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://cuhackyhour.github.io/" # the base hostname & protocol for your site
twitter_username: CUHackyHour
instagram_username: CUHackyHour
timezone: Australia/Perth

# Build settings
markdown: kramdown

github: [metadata]
kramdown:
    input: GFM
    hard_wrap: false
gems:
    - jekyll-coffeescript
    - jekyll-paginate
